name: RestAPI

env:
  AZURE_WEBAPP_NAME: REST_API   # set this to your application's name

on:
  push:
    branches:
      # - master
      # - staging
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    # name: Build a Docker Image and push to I

    steps:

      - uses: actions/checkout@v3
        with:
          ref: feature/level2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: 'Login via Azure CLI'
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Log in to GitHub container registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Lowercase the repo name
#        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

#      - name: 'Build and push image'
#        # uses: azure/docker-login@v1
#        with:
#            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#            username: ${{ secrets.REGISTRY_USERNAME }}
#            password: ${{ secrets.REGISTRY_PASSWORD }}
#      - run: docker build --build-arg APPDIR=/app -f infrastructure/docker/restapi.Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/restapi:${{ github.sha }}-$ENVIRONMENT .

#      - name: 'Build the image'
#        uses: docker/build-push-action@v4
#      - run: docker build --build-arg APPDIR=/app -f infrastructure/docker/restapi.Dockerfile -t r3d-restapi-${{ github.sha }}-$ENVIRONMENT .

# docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/restapi:${{ github.sha }}
# docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/restapi:${{ github.sha }}
#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          file: ./infrastructure/docker/restapi.Dockerfile
#          # tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#          tags: ghcr.io/${{ github.repository }}/restapi:${{ github.sha }}
#- name: Build docker image
#  env:
#    ENVIRONMENT: ${{ env.ENVIRONMENT }}
#  run: docker build --build-arg APPDIR=/app -f infrastructure/docker/restapi.Dockerfile -t r3d-restapi-$ENVIRONMENT .

